Repository cibernox/ember-basic-dropdown, pull requests merged in 2024-06, with the labels that each got.

#903 Document @rootEventType
  docs/app/templates/public-pages/docs/api-reference.hbs
Labels: documentation

#910 Improve `rootEventType` type and export for EPS
  ember-basic-dropdown/src/components/basic-dropdown-content.ts
  ember-basic-dropdown/src/components/basic-dropdown.ts
Labels: enhancement

#927 Fix dropdown not correctly positioned horizontally when body position is relative
  ember-basic-dropdown/src/utils/calculate-position.ts
Labels: bug

#928 Update dependencies
  docs/README.md
  docs/config/ember-cli-update.json
  docs/config/ember-try.js
  docs/package.json
  ember-basic-dropdown/package.json
  package.json
  pnpm-lock.yaml
  test-app/README.md
  test-app/config/ember-cli-update.json
  test-app/config/ember-try.js
  test-app/package.json
Labels: dependencies

#929 Add push dist workflow
  .github/workflows/push-dist.yml
Labels: internal
