Repository cibernox/ember-basic-dropdown, pull requests merged in 2024-01, with the labels that each got.

#731 docs: Bring back missing assets in docs after conversion to v2 addon
  docs/public/ember_logo.png
  docs/public/lts.png
  docs/public/some-image.gif
Labels: bug

#732 Fix blueprint
  ember-basic-dropdown/blueprints/ember-basic-dropdown/index.js
  ember-basic-dropdown/package.json
  ember-basic-dropdown/rollup.config.mjs
Labels: bug

#733 Fix less import & improve docs for less / css
  docs/app/templates/public-pages/docs/installation.hbs
  docs/app/templates/snippets/installation-2.js
  docs/ember-cli-build.js
  ember-basic-dropdown/_index.less
  ember-basic-dropdown/_index.scss
  ember-basic-dropdown/ember-basic-dropdown.less
  ember-basic-dropdown/package.json
Labels: bug, documentation

#735 Add option to use `ember-basic-dropdown.scss`
  ember-basic-dropdown/_index.scss
  ember-basic-dropdown/ember-basic-dropdown.scss
  ember-basic-dropdown/package.json
Labels: enhancement

#736 Types: Separate Args and Signature
  ember-basic-dropdown/src/components/basic-dropdown.ts
Labels: enhancement

#737 DOCS: Fix typos
  docs/app/templates/public-pages/docs/api-reference.hbs
Labels: documentation

#738 Update appReexports
  ember-basic-dropdown/package.json
  ember-basic-dropdown/rollup.config.mjs
Labels: bug

#739 Allow passing attributes in wormhole component & add tests for wormhole
  ember-basic-dropdown/src/components/basic-dropdown-wormhole.hbs
  ember-basic-dropdown/src/components/basic-dropdown-wormhole.ts
  test-app/.eslintrc.js
  test-app/.template-lintrc.js
  test-app/tests/integration/components/basic-dropdown-test.js
  test-app/tests/integration/components/basic-dropdown-wormhole-test.js
Labels: enhancement

#740 Update dependencies
  docs/README.md
  docs/config/ember-cli-update.json
  docs/package.json
  ember-basic-dropdown/package.json
  ember-basic-dropdown/src/components/basic-dropdown-content.ts
  ember-basic-dropdown/src/components/basic-dropdown-trigger.ts
  ember-basic-dropdown/src/components/basic-dropdown.ts
  ember-basic-dropdown/src/modifiers/basic-dropdown-trigger.ts
  pnpm-lock.yaml
  test-app/README.md
  test-app/config/ember-cli-update.json
  test-app/package.json
Labels: dependencies

#743 Remove ember-get-config
  ember-basic-dropdown/package.json
  ember-basic-dropdown/src/components/basic-dropdown-wormhole.ts
  ember-basic-dropdown/src/components/basic-dropdown.ts
  pnpm-lock.yaml
Labels: internal

#765 Update ember cli to v5.6
  docs/config/ember-cli-update.json
  docs/package.json
  pnpm-lock.yaml
  test-app/config/ember-cli-update.json
  test-app/package.json
Labels: dependencies
