Repository cibernox/ember-basic-dropdown, pull requests merged in 2024-03, with the labels that each got.

#791 Add shadow DOM support
  .github/workflows/ci.yml
  docs/package.json
  ember-basic-dropdown/package.json
  ember-basic-dropdown/src/components/basic-dropdown-content.hbs
  ember-basic-dropdown/src/components/basic-dropdown-content.ts
  ember-basic-dropdown/src/components/basic-dropdown.hbs
  ember-basic-dropdown/src/components/basic-dropdown.ts
  ember-basic-dropdown/src/modifiers/basic-dropdown-trigger.ts
  ember-basic-dropdown/src/utils/calculate-position.ts
  pnpm-lock.yaml
  test-app/app/components/shadow-root.hbs
  test-app/app/components/shadow-root.ts
  test-app/app/components/shadow.hbs
  test-app/app/components/shadow.ts
  test-app/app/controllers/application.js
  test-app/app/index.html
  test-app/app/instance-initializers/shadow-root.js
  test-app/app/router.ts
  test-app/app/routes/shadow-root.ts
  test-app/app/styles/app.scss
  test-app/app/templates/application.hbs
  test-app/app/templates/shadow-root.hbs
  test-app/config/environment.js
  test-app/package.json
  test-app/tests/integration/components/basic-dropdown-test.js
  test-app/tests/integration/components/basic-dropdown-wormhole-test.js
  test-app/tests/integration/components/content-test.js
  test-app/tests/integration/components/trigger-test.js
  test-app/tests/unit/routes/shadow-root-test.ts
Labels: enhancement

#813 Remove ember-data (unused package)
  docs/package.json
  docs/types/ember-data/types/registries/model.d.ts
  pnpm-lock.yaml
Labels: internal

#814 Fix snippets in docs
  docs/app/templates/public-pages/cookbook/index.hbs
  docs/app/templates/public-pages/docs/test-helpers.hbs
Labels: documentation

#819 DOCS: Add `destinationElement` to api-reference
  docs/app/templates/public-pages/docs/api-reference.hbs
Labels: documentation

#831 Update ember cli to v5.7
  docs/config/ember-cli-update.json
  docs/config/optional-features.json
  docs/package.json
  ember-basic-dropdown/package.json
  pnpm-lock.yaml
  test-app/config/ember-cli-update.json
  test-app/config/optional-features.json
  test-app/package.json
Labels: dependencies

#832 Fix rollup config (style.js -> styles.js)
  ember-basic-dropdown/rollup.config.mjs
Labels: bug

#834 Fix fastboot `ReferenceError: document is not defined`
  ember-basic-dropdown/src/components/basic-dropdown-wormhole.ts
  ember-basic-dropdown/src/components/basic-dropdown.ts
Labels: bug

#835 Fix fastboot `ReferenceError: document is not defined`
  ember-basic-dropdown/src/components/basic-dropdown-wormhole.ts
  ember-basic-dropdown/src/components/basic-dropdown.ts
Labels: bug

#836 Test Support Helpers: Make scope optional
  ember-basic-dropdown/src/test-support/helpers.ts
Labels: bug

#837 Remove NodeJs info (not necessary for v2 addon)
  ember-basic-dropdown/README.md
Labels: internal
